#!/usr/bin/env python3
"""Static rhetorical signals and body-image role definitions for the planner."""

from __future__ import annotations

import re


# These signals describe rhetorical function rather than a specific industry.
SIGNAL_PATTERNS: dict[str, re.Pattern[str]] = {
    "problem": re.compile(r"问题|痛点|难点|风险|危机|代价|误区|陷阱|焦虑|压力|冲突|失败|困境|瓶颈|挑战|担心|不安|损失|低效|混乱|被动|淘汰|替代|取代|冲击"),
    "promise": re.compile(r"如何|怎么|方法|步骤|指南|清单|路径|建议|方案|策略|技巧|避坑|提升|解决|做好|学会|掌握|快速|高效"),
    "process": re.compile(r"第一|第二|第三|首先|其次|然后|接着|最后|先|再|下一步|步骤|流程|路径|路线|阶段|环节|闭环|链路"),
    "list": re.compile(r"哪些|几个|清单|盘点|类型|分类|包括|分为|主要有|这几类|维度|因素|原因|场景|环节|模块|要点|关键词"),
    "compare": re.compile(r"以前|过去|现在|不再|不是.+而是|对比|区别|差异|从.+到|传统|新旧|前后|左右|相比|变化|升级|转向|替换"),
    "evidence": re.compile(r"数据|比例|增长|下降|案例|报告|研究|调查|统计|成本|效率|收入|规模|数量|趋势|证据|事实|样本|指标|%|％|倍|亿|万"),
    "mechanism": re.compile(r"本质|核心|关键|原因|因为|机制|逻辑|为什么|意味着|真正|底层|原理|规律|决定|影响"),
    "emotion": re.compile(r"焦虑|恐惧|兴奋|震撼|失落|希望|无奈|愤怒|安心|安全感|压迫|孤独|豁然|共鸣|扎心|残酷|委屈|疲惫|沉默|遗憾|勇气|释然|崩溃|倔强|温柔|清醒"),
    "story": re.compile(r"故事|人物|采访|经历|一天|现场|案例|客户|团队|老板|员工|朋友|普通人|一家|一次|亲历|父母|孩子|年轻人|中年人|夜里|路上|饭桌|办公室|出租屋"),
    "principle": re.compile(r"道理|人生|成长|关系|情绪|选择|告别|和解|成熟|清醒|底气|边界|热爱|困住|松弛|内耗|自洽|命运|生活|普通人"),
}

EMOTIONAL_VISUAL_ROLES = {
    "inline_tension",
    "inline_scene",
    "inline_metaphor",
    "inline_emotion",
    "inline_silence",
    "inline_symbolic_scene",
    "inline_human_moment",
}

STRUCTURAL_VISUAL_ROLES = {
    "inline_steps",
    "inline_checklist",
    "inline_light_explainer",
    "inline_data_card",
    "inline_evidence",
}

BODY_ROLE_LIBRARY: dict[str, dict[str, str]] = {
    "inline_light_explainer": {
        "role": "inline_light_explainer",
        "image_type": "light_explainer_illustration",
        "target_effect": "用一个具体场景加少量结构，把这一段的一个判断讲得有用但不拥挤",
        "visual_distance": "中景 / 场景中带少量解释元素",
        "composition": "一个主场景或主对象 + 2到3个短标注、关系线、图标或小节点；最多一条主箭头链",
        "emotional_tone": "清楚、有用、有一点现场感",
        "abstraction_level": "低到中等抽象",
        "information_density": "中等偏轻",
    },
    "inline_explanation": {
        "role": "inline_explanation",
        "image_type": "clean_visual_explanation",
        "target_effect": "把这一段的关键机制讲清楚",
        "visual_distance": "中景 / 单焦点",
        "composition": "一个主对象 + 2到3个辅助元素；可用少量箭头、关系线或简洁标注",
        "emotional_tone": "冷静、清楚、可信",
        "abstraction_level": "低到中等抽象",
        "information_density": "中等",
    },
    "inline_scene": {
        "role": "inline_scene",
        "image_type": "specific_scene",
        "target_effect": "把这一段的真实场景、人物处境或使用现场画出来",
        "visual_distance": "中景或中远景 / 有环境信息",
        "composition": "真实场景驱动，有明确动作、关系或处境",
        "emotional_tone": "有在场感、有代入感",
        "abstraction_level": "低抽象",
        "information_density": "中低",
    },
    "inline_tension": {
        "role": "inline_tension",
        "image_type": "emotional_tension_scene",
        "target_effect": "把这一段的压力、矛盾、风险、选择困难或情绪冲突画出来",
        "visual_distance": "中景 / 人物与压力源或矛盾关系同框",
        "composition": "人物、压力源、后果或选择必须形成一眼可见的关系",
        "emotional_tone": "有张力、有代入、有传播感",
        "abstraction_level": "低到中等抽象",
        "information_density": "中等",
    },
    "inline_contrast": {
        "role": "inline_contrast",
        "image_type": "before_after_or_side_by_side_comparison",
        "target_effect": "把这一段的新旧差异、强弱差异、路线差异或判断差异拉开",
        "visual_distance": "正视角或中景 / 对比式构图",
        "composition": "左右分区、前后对比或上下对照；差异必须一眼看懂",
        "emotional_tone": "理性、有张力",
        "abstraction_level": "中等抽象",
        "information_density": "中等到中高",
    },
    "inline_steps": {
        "role": "inline_steps",
        "image_type": "step_by_step_process_graphic",
        "target_effect": "把这一段的方法、流程、路径或先后顺序画成清楚步骤",
        "visual_distance": "正视角 / 流程视角",
        "composition": "3到5个步骤节点，清晰箭头连接，每步一个短标签或图标",
        "emotional_tone": "清楚、可执行、有掌控感",
        "abstraction_level": "中等抽象",
        "information_density": "中高",
    },
    "inline_checklist": {
        "role": "inline_checklist",
        "image_type": "structured_checklist_or_taxonomy",
        "target_effect": "把这一段的类别、清单、要点、场景或环节归纳成一张图",
        "visual_distance": "正视角 / 分类卡片视角",
        "composition": "3到6个清晰分类卡片或勾选项，每项有图标和极短标签",
        "emotional_tone": "清楚、直接、有收获感",
        "abstraction_level": "中等抽象",
        "information_density": "中高",
    },
    "inline_data_card": {
        "role": "inline_data_card",
        "image_type": "compact_concept_explainer",
        "target_effect": "用克制的概念图，把这一段的结构、判断和关系讲清楚",
        "visual_distance": "概念图 / 轻量解释视角",
        "composition": "一个主对象或主场景 + 2到3个关系模块 + 简洁箭头、图标或关系线",
        "emotional_tone": "理性、有洞察、信息量强",
        "abstraction_level": "中等抽象",
        "information_density": "高但可读",
    },
    "inline_evidence": {
        "role": "inline_evidence",
        "image_type": "evidence_or_data_visual",
        "target_effect": "把这一段的数据、案例、证据或趋势画得可信、清楚",
        "visual_distance": "图表与场景结合 / 编辑图解视角",
        "composition": "一个证据中心，例如趋势线、对比柱、案例卡或文件证据",
        "emotional_tone": "可信、扎实、有判断依据",
        "abstraction_level": "中等抽象",
        "information_density": "中高",
    },
    "inline_detail": {
        "role": "inline_detail",
        "image_type": "focused_detail",
        "target_effect": "放大这一段里最具体的一个动作、对象、界面、材料或局部细节",
        "visual_distance": "近景 / 特写",
        "composition": "细节放大，背景克制，画面只保留一个核心动作或对象",
        "emotional_tone": "专注、具体、可执行",
        "abstraction_level": "低抽象",
        "information_density": "低到中等",
    },
    "inline_metaphor": {
        "role": "inline_metaphor",
        "image_type": "conceptual_metaphor",
        "target_effect": "用一个克制但明确的隐喻延展这一段判断",
        "visual_distance": "中景或远景 / 明确隐喻中心",
        "composition": "单个隐喻主视觉",
        "emotional_tone": "有想象力，但克制",
        "abstraction_level": "中高抽象",
        "information_density": "低",
    },
    "inline_extension": {
        "role": "inline_extension",
        "image_type": "future_or_next_step_scene",
        "target_effect": "顺着这一段观点往前推一步，画出下一步可能发生的场景",
        "visual_distance": "中远景 / 带纵深",
        "composition": "未来感或延展场景，但仍围绕一个中心动作或变化",
        "emotional_tone": "打开感、前瞻感",
        "abstraction_level": "中等抽象",
        "information_density": "中低",
    },
    "inline_emotion": {
        "role": "inline_emotion",
        "image_type": "emotional_pause_visual",
        "target_effect": "让读者在这一段停一下，感受到情绪或判断的分量",
        "visual_distance": "远景或安静中景",
        "composition": "留白更多，节奏放慢，但必须有明确情绪来源",
        "emotional_tone": "沉静、震撼、豁然或有余味",
        "abstraction_level": "中高抽象",
        "information_density": "低",
    },
    "inline_silence": {
        "role": "inline_silence",
        "image_type": "quiet_editorial_illustration",
        "target_effect": "把这一段的余味、迟疑、孤独、释然或没有说出口的情绪画出来",
        "visual_distance": "远景或安静中景 / 留白明显",
        "composition": "一个人物或一个关键物件处在有情绪的空间里；光线、阴影、距离感承担叙事",
        "emotional_tone": "克制、沉静、有余味",
        "abstraction_level": "中等抽象",
        "information_density": "低",
    },
    "inline_symbolic_scene": {
        "role": "inline_symbolic_scene",
        "image_type": "symbolic_story_illustration",
        "target_effect": "把这一段的道理变成一个有冲击力但不说教的象征性场景",
        "visual_distance": "中远景 / 强主视觉",
        "composition": "一个清晰象征物或空间关系承载判断",
        "emotional_tone": "有冲击力、有隐喻感、符合文章调性",
        "abstraction_level": "中高抽象",
        "information_density": "低到中等",
    },
    "inline_human_moment": {
        "role": "inline_human_moment",
        "image_type": "cinematic_human_moment",
        "target_effect": "把这一段落到一个具体人的瞬间，让读者先代入再理解道理",
        "visual_distance": "中景或近景 / 人物瞬间",
        "composition": "一个具体动作、表情或停顿，配合真实空间和少量关键物件",
        "emotional_tone": "真实、有温度、有故事感",
        "abstraction_level": "低到中等抽象",
        "information_density": "低",
    },
}
